version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    env_file:
      - ../.env
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ../scripts:/opt/bitnami/spark/scripts

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    env_file:
      - ../.env
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ../config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ../scripts:/opt/bitnami/spark/scripts

volumes:
  minio_data:
