project_name: "Flight Price Tracker"

data:
  raw_data_path: "./data/raw"
  processed_data_path: "./data/processed"

minio:
  endpoint: "http://localhost:9000"
  access_key: "admin"
  secret_key: "admin123"
  bucket_name: "flight-data"

presto:
  host: "localhost"
  port: 8080
  catalog: "minio"
  schema: "flight"
